# 선형연립방정식


$$
\begin{align}
\begin{matrix}
x_1 & + & x_2 &   &     & = & 2  \\
    &   & x_2 & + & x_3 & = & 2  \\
x_1 & + & x_2 & + & x_3 & = & 3  \\
\end{matrix}
\tag{2.4.1}
\end{align}
$$


**계수행렬(coefficient matrix), 미지수벡터(unknown vector), 상수벡터(constant vector)**


$$
\begin{align}
A = 
\begin{bmatrix}
 1 & 1 & 0 \\
 0 & 1 & 1 \\
 1 & 1 & 1 \\
\end{bmatrix}, \;\;\;
x = \begin{bmatrix}
x_1 \\ x_2 \\ x_3
\end{bmatrix}, \;\;\;
b = \begin{bmatrix}
2 \\ 2 \\ 3
\end{bmatrix}
\tag{2.4.7}
\end{align}
$$


## 역행렬


$$
A = \begin{pmatrix} a_{11} & a_{12} \\
a_{21} & a_{22} \end{pmatrix} 일 때\\
\\
A^{-1} = \frac{1}{a_{11}a_{22}-a_{12}a_{21}}
\begin{pmatrix} a_{22} & -a_{12} \\
-a_{21} & a_{11} \end{pmatrix}
$$

역행렬 구할 때는 $a_{11}a_{22}-a_{12}a_{21}\ne0$ 인지 여부를 확인해야 한다.

In [2]:
import numpy as np

In [3]:
A = np.array([[5,3],[2,1]])
A

array([[5, 3],
       [2, 1]])

In [7]:
np.linalg.det(A)

-1.0000000000000002

In [9]:
A_ = np.linalg.inv(A)
A_

array([[-1.,  3.],
       [ 2., -5.]])

In [11]:
(A @ A_).astype(np.int16)

array([[1, 0],
       [0, 1]], dtype=int16)

In [12]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])

In [13]:
np.linalg.det(A)

1.0

In [14]:
A_ = np.linalg.inv(A)
A_

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [15]:
A @ A_

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])