# 선형연립방정식


$$
\begin{align}
\begin{matrix}
x_1 & + & x_2 &   &     & = & 2  \\
    &   & x_2 & + & x_3 & = & 2  \\
x_1 & + & x_2 & + & x_3 & = & 3  \\
\end{matrix}
\tag{2.4.1}
\end{align}
$$


**계수행렬(coefficient matrix), 미지수벡터(unknown vector), 상수벡터(constant vector)**


$$
\begin{align}
A = 
\begin{bmatrix}
 1 & 1 & 0 \\
 0 & 1 & 1 \\
 1 & 1 & 1 \\
\end{bmatrix}, \;\;\;
x = \begin{bmatrix}
x_1 \\ x_2 \\ x_3
\end{bmatrix}, \;\;\;
b = \begin{bmatrix}
2 \\ 2 \\ 3
\end{bmatrix}
\tag{2.4.7}
\end{align}
$$


## 역행렬


$$
A = \begin{pmatrix} a_{11} & a_{12} \\
a_{21} & a_{22} \end{pmatrix} 일 때\\
\\
A^{-1} = \frac{1}{a_{11}a_{22}-a_{12}a_{21}}
\begin{pmatrix} a_{22} & -a_{12} \\
-a_{21} & a_{11} \end{pmatrix}
$$

역행렬 구할 때는 $a_{11}a_{22}-a_{12}a_{21}\ne0$ 인지 여부를 확인해야 한다.

In [2]:
import numpy as np

In [3]:
A = np.array([[5,3],[2,1]])
A

array([[5, 3],
       [2, 1]])

In [7]:
np.linalg.det(A)

-1.0000000000000002

In [9]:
A_ = np.linalg.inv(A)
A_

array([[-1.,  3.],
       [ 2., -5.]])

In [11]:
(A @ A_).astype(np.int16)

array([[1, 0],
       [0, 1]], dtype=int16)

In [12]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])

In [13]:
np.linalg.det(A)

1.0

In [14]:
A_ = np.linalg.inv(A)
A_

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [15]:
A @ A_

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 역행렬과 선형연립방정식 해

역행렬과 연립방정식

역행렬을 사용하면 **연립방정식**을 풀수 있다. 
 - 역행렬 이용
 - SymPy 이용

프로그래밍 언어에서 연립방정식을 직접 풀어야 하는데 이때 **역행렬**이 큰 역할을 한다.

아래 같은 연립방정식이 있다.

$$
5x + 3y = 9\\
2x + y = 4
$$

방정식을 행렬로 표현하면 

$$
\begin{pmatrix}5 & 3 \\ 2 & 1 \end{pmatrix}
\begin{pmatrix}x \\y \end{pmatrix} = 
\begin{pmatrix}9 \\4 \end{pmatrix}
$$



연립방정식을 행렬을 이용해 풀기위해서 행렬의 다음 두 특성이 중요하다.

 - 행렬과 역행렬을 곱하면 단위행렬이 된다.
 - 어떤 행렬을 단위행렬에 곱한 결과는 원래 행렬이다.

행렬 $\begin{pmatrix}5 & 3 \\ 2 & 1 \end{pmatrix}$ 의 역행렬을 양변에 곱하면

$$
\begin{pmatrix}-1 & 3 \\ 2 & -5 \end{pmatrix}
\begin{pmatrix}5 & 3 \\ 2 & 1 \end{pmatrix}
\begin{pmatrix}x \\y \end{pmatrix} = 
\begin{pmatrix}-1 & 3 \\ 2 & -5 \end{pmatrix}
\begin{pmatrix}9 \\4 \end{pmatrix}
$$

이 식을 정리하면

$$
\begin{pmatrix}1 & 0 \\ 0 & 1 \end{pmatrix}
\begin{pmatrix}x \\y \end{pmatrix} = 
\begin{pmatrix}-1 & 3 \\ 2 & -5 \end{pmatrix}
\begin{pmatrix}9 \\4 \end{pmatrix}
$$

단위행렬은 어떤 행렬을 곱해도 원래 행렬과 같으므로 좌변을 다음 같이 쓸 수 있다.

$$
\begin{pmatrix}x \\y \end{pmatrix} = 
\begin{pmatrix}-1 & 3 \\ 2 & -5 \end{pmatrix}
\begin{pmatrix}9 \\4 \end{pmatrix}
$$

이것을 풀면

$$
\begin{pmatrix}x \\y \end{pmatrix} = 
\begin{pmatrix}-1\times 9 + 3\times4 \\ 2\times 9 + -5\times4 \end{pmatrix} =
\begin{pmatrix}3 \\-2 \end{pmatrix}
$$

컴퓨터 프로그래밍으로 이것을 적용하면 **식**에 따라서 계산하는 방법이 달라지므로 프로그래밍으로 구현하기 어렵다. 그러나 행렬을 사용하면 다음 순서로 계산할 수 있다.

1. 연립방정식을 행렬로 나타낸다
2. 미지의 계수로 만든 행렬의 역행렬을 구한다.
3. 구한 역행렬을 1의 식 우변에 곱한다.


In [16]:
A = np.array([[5,3],[2,1]])
B = np.array([[9],[4]])

In [17]:
np.linalg.det(A)

-1.0000000000000002

In [18]:
A_ = np.linalg.inv(A)
A_

array([[-1.,  3.],
       [ 2., -5.]])

In [19]:
A @ A_

array([[1.00000000e+00, 1.77635684e-15],
       [2.22044605e-16, 1.00000000e+00]])

In [21]:
A_ @ B

array([[ 3.],
       [-2.]])

In [25]:
A = np.matrix([[5,3],[2,1]])
B = np.matrix([[9],[4]])

In [24]:
type(A)

numpy.matrix

In [26]:
A_ = np.linalg.inv(A)

In [27]:
A_ * A

matrix([[1.00000000e+00, 0.00000000e+00],
        [1.77635684e-15, 1.00000000e+00]])

In [28]:
A_ * B

matrix([[ 3.],
        [-2.]])

sympy

In [30]:
from sympy import Symbol, solve

x, y = Symbol('x'), Symbol('y')

In [32]:
x, y, type(x)

(x, y, sympy.core.symbol.Symbol)

In [33]:
ex1 = 5*x + 3*y - 9
ex2 = 2*x + y - 4

In [36]:
ex1, ex2

(5*x + 3*y - 9, 2*x + y - 4)

In [38]:
solve((ex1, ex2))

{x: 3, y: -2}