
# 04.벡터

참고
 - 파이썬으로 배우는 핵심 고등수학
 - https://m.blog.naver.com/forfriend5/220599558731


### 4.1.2 벡터의 성분

벡터는 **방향과 크기가 중요하고 위치는 중요하지 않다**. 한 점에서 다른 점의 벡터를 $\overrightarrow{AB}$ 로 표시한다.

그림 같이 방향과 크기가 같고 다른 위치의 벡터를 **위치벡터**라고 한다.

<img src='https://mblogthumb-phinf.pstatic.net/20160116_152/forfriend5_1452944236142GI7mb_PNG/%C1%A6%B8%F1_%BE%F8%C0%BD4_%BA%B9%BB%E7.png?type=w2' width='400'>

벡터의 시작점을 좌표축의 원점으로 이동하면 $\overrightarrow{OC}$ 는 끝점의 좌표를 사용하여 다음과 같이 나타낼 수 있다.

$$
\overrightarrow{OC} = (2,3)
$$

이것을 벡터의 성분 표시 (혹은 요소 표시)라고 하며 x의 값을 x 성분, y 값을 y 성분이라고 한다.성분을 세로로 나열해서 아래 같이 쓰기도 한다.

$$
\overrightarrow{OC} = {2 \choose 3}
$$



##### 벡터의 성분 구하기

벡터의 시작점 A(x,y) 에서 끝점 B(x2,y2) 를 다음 같은 방식으로 구한다.

$$
\overrightarrow{AB} = {x_2 - x_1 \choose y_2 - y_1}
$$

예를 들어 A(6, 5), B(4,2) 의 벡터는 

$$
\overrightarrow{AB} = { 6 - 4 \choose 5 - 2 } \\
 = { 2 \choose 3 }
$$

### 4.1.3 벡터의 방향

성분을 표기한 벡터는 부호를 보면 방향을 알 수 있다.
 - x 성분이 양수면 왼쪽에서 오른쪽
 - x 성분이 음수면 오른쪽에서 왼쪽
 - y 성분이 양수면 위로 향하는 벡터
 - y 성분이 음수면 아래로 향하는 벡터
 

벡터의 끝점에서 x축 방향으로 수선을 내리면 좌표상의 삼각형과 같은 모습이다.

<img src='https://t1.daumcdn.net/cfile/tistory/2501E63C5463FE4030' width='350'>

벡터 x, y 성분을 알고 있으므로 x축과 벡터가 이루는 각도는 탄젠트의 역함수를 사용해 다음 같이 나타낼 수 있다. ([3.4.4 삼각비와 각도](03_방정식_도형.ipynb#3.4.4-삼각비와-각도))

$$
\theta = tan^{-1} \left( \frac{y}{x} \right)
$$

원점 O(0,0)에서 A(2,3) 까지 벡터 $\overrightarrow{OA}$ 의 각도를 파이썬으로 다음 같이 구할 수 있다.

```
math.atan2(y, x)
```
 - math 모듈 설명: https://wikidocs.net/21116

In [1]:
import math
rad = math.atan2(3,2) #라디안(높이, 밑변)
th = math.degrees(rad) #도수법
th

56.309932474020215

각도를 구할 때 x축의 양의 방향을 0으로 정하고, 귀로 향한 벡터의 각도는 반시계 방향으로 0~180도, 아래로 향한 벡터의 값은 0~-180도 사이 값이 된다.

### 4.1.4 벡터의 크기

벡터 크기는 피타고라스 정리로 구할 수 있다.  벡터의 크기는 $a=<a1,a2>$일 때  

$$
\left| a \right| =\sqrt { { a }_{ 1 }^{ 2 }+{ a }_{ 2 }^{ 2 } } 
$$

이다.예를 들어 $\overrightarrow{OA}$는 x 성분이 2, y 성분이 3으로 

$$
\left|\overrightarrow{AB}\right| = \sqrt{2^2 + 3^2} \\
 = \sqrt{13}
$$

> 벡터를 $|\overrightarrow{OA}|$  같이 표현하면 **벡터의 크기**를 나타내고, 숫자 값이다. 벡터 처럼 양을 가지는 것과 구별해서 **스칼라**라고 말한다.



예를 들어 $\vec{a}=(-\frac{2}{7}, \frac{3}{7}, \frac{6}{7})$ 크기는?

크기를 피타고라스 정리로 계산해 보자.

In [2]:
import numpy as np

# 식으로 계산
a = np.array([-2/7,3/7,6/7])
norm_a = np.sqrt(a[0]**2 + a[1]**2 + a[2]**2)
norm_a

0.9999999999999999

NumPy에서 numpy.linalg.norm()으로 계산할 수 있다. 

In [3]:
import numpy.linalg as lin
lin.norm(a)

0.9999999999999999

##### 단위 벡터

**단위벡터**는 방향은 같고 크기가 1인 벡터를 나타내고 $\vec{e}$ 로 표현한다.

$$
\vec{e} = \frac{\overrightarrow{AB}}{\left|\overrightarrow{AB}\right|}
$$

크기가 1이기만 하면 단위벡터이므로 모든 방향으로 단위벡터가 존재한다. 

---

### 특수한 벡터


#### 영 벡터

모든 원소가 0인 N차원 벡터는

$0_N = 0 = \begin{bmatrix} 0 \\ 0 \\ \vdots \\ 0\end{bmatrix} $

문맥에서 벡터의 크기를 알 수 있을 때는 크기를 나타내는 아래첨자를 생략할 수 있다.

In [4]:
# 영벡터
np.zeros((1,4))

array([[0., 0., 0., 0.]])

#### 일 벡터

모든 원소가 1인 N차원 벡터,

$1_N = 1 = \begin{bmatrix} 1 \\ 1 \\ \vdots \\ 1\end{bmatrix} $




In [5]:
#일벡트
np.ones((1,4))

array([[1., 1., 1., 1.]])

### 4.1.5 벡터의 연산

현재 사람이 서있는 곳에서 어떤 캐릭터가 오른쪽으로 300m 가고, 그곳에서 위로 400m 갔고 이곳이 목적지이다. 현재 위치에서 목적지는?

시작점 밑변 300, 높이 400 의 삼각형 모습이고 시작점에서 목적지 까지 벡터.

벡터는 벡터끼리 덧셈, 뺄셈이 가능하고 실수배하면 방향을 바꾸지 않고 크기만을 바꿀 수 있다. 이와 같은 연산은 벡터의 성분끼리 수행된다.

- 참조: https://mrw0119.tistory.com/10

#### 덧셈

벡터 $\vec{a} + \vec{b} = \vec{c}$ 가 된다.

<img src='https://mblogthumb-phinf.pstatic.net/20160115_148/forfriend5_1452858576774WOjtE_PNG/%C1%A6%B8%F1_%BE%F8%C0%BD6.png?type=w2' width='400'>

벡터는 아래 그림같이 처럼 교환이 가능하다.  

<img src='images/vector_plus.png' width='400'>

이것은 $\vec{a} + \vec{b} = \vec{b} +  \vec{a}$

덧셈을 벡터의 성분으로 나타내면

$$
\vec{a} = { a_1 \choose a_2 }, \vec{b} = { b_1 \choose b_2 } 일 때 \\
\vec{a} + \vec{b} = { a_1 \choose a_2 } + { b_1 \choose b_2 } \\
 = { a_1 + b_1 \choose a_2 + b_2 }
$$

#### 문) 점 P1(4,6,-2), P2(1,8,3) 사이 벡터 $\overrightarrow{P1P2}$는?

NumPy로 벡터 계산이 가능하다. numpy.array 배열을 사용한다.

In [55]:
import numpy as np

a = np.array([4,6,-2])
b = np.array([1,8,3])

b - a

array([-3,  2,  5])

다음 같이 ${ a_1 \choose a_2 }, { b_1 \choose b_2 }$ 으로 치환해 계산해도 동일하다.

In [56]:
a = np.array([4,6,-2]).reshape(3,1)
b = np.array([1,8,3]).reshape(3,1)
b-a

array([[-3],
       [ 2],
       [ 5]])

#### 뺄셈

벡터 $\vec{b}$ 에 -부호를 붙여 $-\vec{b}$ 크기는 같지만 방향이 반대인 벡터가 된다.

그림은 벡터 $\vec{a}$ 에 $\vec{b}$를 뺀 것으로,  같이 $\vec{a} - \vec{b} = \vec{c}$ 이다.

이것은  $\vec{a} +(-\vec{b}) = \vec{c}$ 같이 덧셈으로 쓸 수 있다. 

<img src='images/vector_minus.png' width='400'>

벡터의 뺄셈을 성분으로 계산해 보면,


$$
\vec{a} = { a_1 \choose a_2 }, \vec{b} = { b_1 \choose b_2 } 일 때 \\
\vec{a} - \vec{b} = { a_1 \choose a_2 } - { b_1 \choose b_2 } \\
 = { a_1 - b_1 \choose a_2 - b_2 }
$$

#### 실수배

벡터에 임의 실수 k 를 곱하면 방향은 바꾸지 않고 크기만 변경된다.

<img src='images/vector_double.png' width='200'>

$$
\vec{a} = { a_1 \choose a_2 } 일 때 \\
\vec{b} = k\vec{a} = {ka_1 \choose ka_2}
$$

##### 파이썬 벡터 연산

벡터 $\vec{a}$ 성분 (2,2)이고 $\vec{b}$ 성분은 (2,-1) 이다.

In [57]:
import numpy as np

a = np.array([2,2])
b = np.array([2,-1])

In [5]:
a + b, a - b, 2 * a

(array([4, 1]), array([0, 3]), array([4, 4]))

### 4.1.6 벡터의 분해

벡터 연산에서 두 벡터가 이루는 평행사변형의 대각선이 $\vec{a} + \vec{b}$ 가 된다. 이것은 벡터는 **두 벡터로 분해할 수 있다**로 해석이 된다.

<img src='images/vector_disjoint.png' width='300'>

- 참조: https://mrw0119.tistory.com/12?category=865489


사람이 공을 던지면 궤도를 그리면 날아간다. 공을 *어떤 방향으로 얼만큼 힘을 주어 던졌는지* 알면 계산을 통해 이 궤도를 구할 수 있다. **어떤 방향으로 얼만큼의 힘** 은 벡터를 표현한다. 이것은 물리 세계에서 *초기속도*라고 한다.

공의 궤적을 계산하려면 수평 방향의 속도와 수직 방향의 속도가 필요하다 
 - *공은 수평 방향으로 등속운동을 하고, 수직방향으로 등가속 운동을 한다*. 
 - 이 수평, 수직 방향의 속도를 구하기 위해 벡터를 분해한다.

초기 속도 $\vec{v}$ 는 x, y 축으로 수선을 내린 모습으로 수평/수직 방향 벡터 $\vec{a},\vec{b}$ 같이 분해할 수 있다.

<img src='images/vector_disjoint2.png' width='300'>

그리고 등속도 운동과 등가속도 운동의 공식에 따라 시간당 공의 이동량을 계산하면 궤적을 시뮬레이션 할 수 있다.

---

## 벡터의 방정식

**도형을 벡터에 대한 식**으로 표현한 것을 벡터의 방정식이라 한다.

### 4.2.1 직선을 나타내는 방법

직선의 방정식은 두 점을 잇는 선을 그을 수 있다. 벡터의 개념을 도입하면 직선을 긋기 위해 필요한 것은 **직선의 방향**과 **직선상의 한 점** 이란 두 가지 이다.

점 A를 지나며 $\vec{v}$ 에 평행한 직선.

<img src='images/vector_parallel_A.png' width='200'>


이 직선에 한 점 P를 찍으면 $\overrightarrow{AP}$ 는 $\vec{v}$ 와 방향은 같고 크기가 다른 벡터이므로 $\overrightarrow{AP} = k\vec{v}$ 로 나타낼 수 있다. 

<img src='images/vector_A_P.png' width='200'>

좌표 원점에서 점A, P를 가르키는 벡터를 a, p라 하면 아래 식이 성립하고 이것이 직선을 나타내는 **벡터 방정식**이다.

$$
\vec{p} = \vec{a} + k\vec{v}
$$
 - k는 임의 실수

##### 예) 

벡터 방정식이 직선의 방정식을 나타내는지 직선의 방정식이 아닌 벡터 방정식에 값을 넣어 확인해 보자.

점 A(-1,2), 목적지 점 P(2,4) 의 방향으로 벡터 $\vec{v}$ 는 벡터의 A, P의 성분으로

<img src='images/vector_ex_A_to_P.png' width='300'>

직선의 방향 벡터v는 
$$
\vec{v} = { 2-(-1) \choose 4-2 } = (3,2)
$$



벡터 $\vec{v}$ 와 점A로 향하는 벡터 $\vec{a}$ 의 성분 (-1,2)를 벡터 방정식에 대입하면 점 P의 좌표 (x,y)는 

$$
{x \choose y } = {-1 \choose 2} + k{3 \choose 2}
$$

위 식을 x, y에 대해 풀면 y = ax + b 형태의 식이 되므로 

$$
x = -1 + 3k \quad\longleftarrow 1\\
y = 2 + 2k \quad\longleftarrow 2
$$

여기에 k를 소거하기 위해 위 두 식1의 양변에 2를 곱하고 식2의 양변에 3을 곱하면

$$
2x = -2 + 6k \\
3y = 6 + 6k \\
$$

이제 식4에서 식5를 빼고 이를 y에 대해서 풀면 y=ax+b 형태의 직선의 방정식이 된다.

$$
2x - 3y = 8 \\
\\
\therefore y = \frac{2}{3}x + \frac{8}{3}
$$


#### 두 점을 잇는 직선의 방정식

앞의 그림의 좌표를 이용해 직선의 방정식을 구해보면

(-1,2), (2,4)를 y=ax+b 에 대입해 보면

$$
-a + b = 2 \quad \cdots \ (-1,2) \\
2a + b = 4 \quad \cdots (2,4)
$$

a, b 에 대해서 풀면

$$
a = \frac{2}{3},\ b = \frac{8}{3}
$$


sympy 로 풀기 위해서 ax + b + c = 0 형식으로 고쳐서 푼다.

In [9]:
from sympy import Symbol, solve
a, b = Symbol('a'), Symbol('b')

ex1 = -1 * a + b - 2
ex2 = 2 * a + b -4
solve((ex1, ex2))

{a: 2/3, b: 8/3}

### 두 직선의 교점

3.3.3에서 두 직선의 식을 연립방정식으로 만들어 교점의 좌표를 구했다. 다음 같이 4 점을 연결한 선의 교점을 구해보자.

<img src='images/vector_crosspoint_two_lines.png' width='200'>

이 교점은 1) 두 직선의 방정식을 구한다. 2) 두 식을 연립방정식으로 푼다. 같이 해결이 가능하다. (3.3.3)

여기서는 벡터 방정식을 사용해 보자,

AB, CD 선의 교점 P를 벡터 방정식으로 나타내 보자,

<img src='images/vector_crosspoint_two_lines2.png' width='300'>

원점 O에서 점P에 대한 벡터 방정식은 아래 같다. 두 직선의 기울기가 다르므로 k, t 를 사용한다.

$$
\overrightarrow{OP} = \overrightarrow{OA} + k\overrightarrow{AB} \quad (k는 실수) \\
\overrightarrow{OP} = \overrightarrow{OC} + t\overrightarrow{CD} \quad (t는 실수)
$$

이 두 식을 풀면 
$$
\overrightarrow{OA} + k\overrightarrow{AB} = \overrightarrow{OC} + t\overrightarrow{CD}
$$



위 식을 풀면 교점의 P 좌표를 알 수 있다. 예를 들어 A(2,7), B(6,1) 과 C(2,3), D(6,5) 일 때 위 식에 대입하면

$$
{ 2 \choose 7 } + k{ 6-2 \choose 1-7} = { 2 \choose 3 } + t{ 6-2 \choose 5-3 }
$$

이 식을 정리하면

$$
{ 2 + 4k \choose 7 - 6k } = { 2 + 4t \choose 3 + 2t }
$$

각 성분에 대해 식을 써서 정리하면 아래 같은 연립방정식이 된다.

$$
4k - 4t  = 0 \\
-6k - 2t + 4 = 0
$$

이식을 풀어 k, t를 구하면

In [11]:
from sympy import Symbol, solve

k = Symbol('k')
t = Symbol('t')

ex1 = 4*k - 4*t
ex2 = -6*k - 2*t + 4
solve((ex1, ex2))

{k: 1/2, t: 1/2}

이 값을 $\overrightarrow{OA} + k\overrightarrow{AB}$ 식에 대입하면 점 P의 좌표는 (4,4)이다.

$$
{ 2 \choose 7 } + \frac{1}{2} { 6-2 \choose 1-7} = { 2 + 2 \choose 7 - 3 } = { 4 \choose 4 }
$$

### 4.2.3 벡터를 사용하는 이유

앞의 교점을 구할 때 연립방정식을 푸는 것은 - 주어진 좌표를 가지고 직선의 식을 만들고 그 식들로 연립방정식을 만들어 해를 구하는게 직관적이고 이해가 쉽다. 그러나 이것은 x, y축의 평면좌표에서 일어나는 일이다. 만약 z축 같은 삼차원 좌표에서는 미지수가 한개 더 늘어나서 $ax+by+cz+d=0$ 라는 식이 된다. 계산 복잡도가 늘어난다.

그러나 벡터에서는 아래 같이 성분을 하나 추가하면 된다.

$$
\vec{v} = \begin{pmatrix} x \\ y \\ z \end{pmatrix}
$$


그래서 공간에서 벡터 방정식은 아래 같이 나타낼 수 있다.

$$
\vec{p} = \vec{a} + k\vec{v} \quad (k는 임의 실수)
$$

앞의 벡터 방정식과 같다. 이차원, 삼차원 이든 같은 계산법으로 풀 수 있다. 이것이 벡터를 사용하는 가장 큰 이유이다.

#### 공간도형과 벡터

아래 그림은 오른쪽 좌표계로 x축은 오른쪽이 양의 방향이고, y축은 위쪽이 양의 방향이다. 뒤에서 앞으로 z축을 포함해 3차원 공간을 나타낸다.

<img src='images/coord_left_right_hand.png' width='300'> <img src='images/coord_left_right_P.png' width='300'>

좌표계에서 x,y,z 좌표를 추가해 표현한다.

$$
\overrightarrow{OP} = (3,4,2) \quad \overrightarrow{OP}=\begin{pmatrix} 3 \\ 4 \\ 2 \end{pmatrix}
$$

3개의 벡터는 아래 같이 z성분을 추가해 계산한다.

$$
\vec{a}=\begin{pmatrix} a_1 \\ a_2 \\ a_3 \end{pmatrix}, \quad \vec{b}=\begin{pmatrix} b_1 \\ b_2 \\ b_3 \end{pmatrix} 일 때\\
\\
\vec{a}+\vec{b} = \begin{pmatrix} a_1 \\ a_2 \\ a_3 \end{pmatrix} + \begin{pmatrix} b_1 \\ b_2 \\ b_3 \end{pmatrix} = \begin{pmatrix} a_1+b_1 \\ a_2+b_2 \\ a_3+b_3 \end{pmatrix}
$$

그리고 $\vec{v}=(x,y,z)$일 때 $\vec{v}$의 크기는 아래 같이 구할 수 있다.

$$
\left| \vec{v} \right| = \sqrt{x^2+y^2+z^2}
$$


---

## 벡터의 내적

벡터는 방향과 크기를 화살표로 표현해 도형으로 다룰수 있다는 장점이 있다(기하벡터). 성분으로 표기할 때는 수식으로 다룰 수 있는 특징이 있다.

여기서 벡터가 CG, Game 등에서 어떻게 다뤄지는지 확인해 본다.



### 4.3.1 기여도 계산하기

아래 그림 처럼 서로 다른 방향으로 물건을 끄는 상황에서, 영희가 A방향으로 10 만큼의 힘으로 상자를 끌고 있고, 철수가 B방향으로 10만큼 힘으로 끌고 간다. 만약 철수가 A방향으로 끌고 가면 철수는 영희에게 100% 기여하게 된다.

<img src='images/vector_chulsoo_younghee.png' width='300'>

철수 벡터에서 영희쪽으로 수선을 내리면 직각삼각형이 만들어진다. 이 삼각형 밑변F 이 영희가 끌고 있는 방향에 대한 철수의 기여도가 된다.

<img src='images/vector_chulsoo_younghee2.png' width='200'>

철수 벡터가 영희쪽으로 가까울 수록 직각삼각형 밑변은 길어진다 - 더 많은 기여를 한다. 반대로 멀어지면 짭아지며 기여가 낮은 것이다.

이런 변화를 알아보기 위해서 반지름 1인 단위원을 그려보자. x축을 영희 방향, y축의 철수 방향에서 길이가 1인 x방향의 수선을 내리면 직각삼각형과 닮은 삼각형이 원에 생긴다.

<img src='images/vector_chulsoo_younghee3.png' width='400'>

이 직각삼각형의 빗변과 밑변의 비율은 $1:cos\theta$ 로 표현되므로, 철수 방향의 벡터 $\vec{a}$ 라고 하면 아래 비례식이 성립한다.

$$
\left|\vec{a}\right| : F = 1 : cos\theta
$$

이 비례식을 밑변 F 중심으로 변형하면

$$
F =  \left|\vec{a}\right| cos\theta
$$




#### 예)

길동과 서희의 벡터가 이루는 각도가 60도이고 길동이 끄는 힘이 10이라면 길동의 기여도는

In [12]:
import math

10 * math.cos(math.radians(60))

5.000000000000001

### 4.3.2 일의 양 계산하기

그림 처럼 10의 힘으로 3m를 움직이면 물리 세계에서 *크기x이동거리* 로 10x3=30 만큼 일을 한다고 한다. 이때 힘을 준 방향과 움직인 거리는 같아야 한다.

<img src='images/vector_pulling.png' width='550'>

그럼 캐리어와 같이 바퀴 달린 물건을 비스듬히 10만큼 힘으로 끌게 되면 수평 방향으로 일정하기 100% 힘이 작용하지 않는다. 이것은 앞의 4.3.1의 기여도 같은 계산으로 작용한 힘은 $10\times cos60 = 5$ 같다. 즉 10의 힘이지만 5만큼 기여해서 5x3=15 만큼 일을 한것이 된다.

### 4.3.3 벡터의 내적

앞의 4.3.2 일의 양 계산하기에서 "힘의 크기x이동 거리" 로 일의 양을 계산한 것은 수학 세계에서 **벡터의 내적** 이라고 말한다.

**.** 을 사용해서 아래 같이 표현한다.

$$
\vec{a} \cdot \vec{b} = \left|\vec{a}\right| \left|\vec{b}\right| cos\theta \quad \longleftarrow 식2
$$

위 식은 아래 그림같이 $|\vec{a}|cos\theta$ 에서 $\vec{a}$의 방향으로 끌었을 때 수평 방향으로 작용하는 힘(F)이고 $\vec{b}$는 해당 방향으로 움직인 거리이다.

<img src='images/vector_amount_power_move.png' width='200'>



#### 벡터의 곱

두 벡터의 곱셈은 여러 방법이 있지만 여기서 **내적(inner product)**만을 다룬다. 벡터 x와 y의 내적은 다음 처럼 표시한다.

$$ x^Ty$$

내적은 점(dot)로 표기하는 경우도 있어 닷 프러덕트(dot product)라고도 한다. $<x, y>$ 기호로 나타낼 수 도 있다.

$$ x\cdot y = <x, y> = x^Ty$$




두 벡터를 내적하려면 다음과 같은 조건이 만족해야 한다.
  - 우선 두 벡터의 길이가 같아야 한다.
  - 앞의 벡터가 **행 벡터**이고 뒤의 벡터가 **열 벡터**야 한다.
 - 행렬 곱 A*B에 대해 A의 열의 수와 B의 행의 수가 같아야 한다.
 - 결국 A행과 B열의 개수를 가진다.
 - 단, 교환법칙은 성립하지 않는다.

 
벡터 내적에 대해 [벡터의 분해](http://mrw0119.tistory.com/12) 에서 내적에 대한 풀이를 볼 수 있다.

벡터의 성분을 알고 있다면 아래 같이 계산할 수 있다.

$$
\vec{a} = {a_1 \choose a_2}, \quad \vec{b} = {b_1 \choose }\\
\\
\vec{a}\cdot\vec{b} = a_1b_1 + a_2b_2 \quad \longleftarrow 식3
$$

내적의 계산은 위 *식2* 와 *식2* 를 이용해 계산한다. 벡터의 내적으로 얻을 수 있는 것으:

1. **내적을 계산한 결과는 벡터의 형태가 아니고 스칼라 형태**
2. **두 벡터가 이루는 각도를 구할 수 있다**(cos 값)
3. **내적을 계산한 결과를 보면 두 벡터의 위치 관계를 알 수 있다**

### 4.3.4 두 직선을 이루는 각도

내적을 계산하는 두 식은 같으므로 다음이 성립한다.

$$
\left| \vec{a} \right| \left| \vec{b} \right| cos \theta = a_1b_1 + a_2b_2
$$

이 식을 정리하면 다음 같이 벡터의 내적을 이용해 **두 벡터가 이루는 각도를 구할 수 있다**

$$
cos\theta = \frac{ a_1b_1 + a_2b_2}{\left| \vec{a} \right| \left| \vec{b} \right|} \quad \longleftarrow 식4
$$

점A-B, 점C-D 를 연결한 교차점 세타를 벡터의 내적을 이용해 구해보자.

<img src='images/vector_innerproduct_ABCD.png' width='300'>

A-B의 벡터를 $\vec{a}$, C-D의 벡터를 $\vec{b}$ 를 성분으로 나타내면

$$
\vec{a}={x_2 - x_1 \choose y_2 - y_1 }, \quad \vec{b}={x_4 - x_3 \choose y_4 - y_3 }
$$

벡터의 크기를 피타고라스 정리를 이용해 구한다.

$$
|\vec{a}| = \sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}\\
|\vec{b}| = \sqrt{(x_4-x_3)^2 + (y_4-y_3)^2}
$$

이 두 식을 식4에 대입하면 두 벡터가 이루는 각을 얻을 수 있다.

$$
cos\theta = \frac{ x_1y_1 + x_2y_2 + x_3y_3 + x_4y_4}{\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}
\sqrt{(x_4-x_3)^2 + (y_4-y_3)^2}} \quad \longleftarrow 식4-1
$$

##### 문) 내적의 공식을 이용해 두 직선이 이루는 각을 구해보자,

아래 그림의 두 직선이 교차하는 곳의 내적을 공식을 이용해 계산해 보자,

<img src='images/vector_innerproduct_ex_ABCD.png' width='300'>



In [2]:
import math
import numpy as np

# 좌표
a = np.array([2,7])
b = np.array([6,1])
c = np.array([2,3])
d = np.array([6,5])

# 벡터 a와 b의 성분
va = b - a
vb = d - c

# 벡터의 크기
norm_a = np.linalg.norm(va)
norm_b = np.linalg.norm(vb)

# 벡터의 내적
dot_ab = np.dot(va, vb)

# 교점 각 구하기
cos_th = dot_ab / (norm_a * norm_b)
rad = math.acos(cos_th)
deg = math.degrees(rad)
print(deg)

82.8749836510982


벡터 내적의 결과가 cos 이라서 각도로 변환하려면 acos 을 사용해야 한다. 그리고 acos 결과는 호도법으로 도수법으로 변환해서 사용한다.

### 4.3.5 내적의 성질

크기가 1인 단위 벡터로 내적을 계산하면 $cos\theta$ 값은 -1~1 범위이다.

내적을 계산한 결과가 양수일 때는 
 - 두 벡터가 이루는 각도가 예각(90이하)입니다.
 - 0일 때는 직각

음수 일 때는
 - 둔각(90보다 큼) 이다.

보통 이 성질은 삼차원 그래픽스, 게임에서 캐릭터를 랜더링 할지 여부를 판단할 때 사용.

<img src='images/vector_innerproduct_view.png' width='300'>

위 그림 같이 시점 방향의 벡터 $\vec{a}$ 라 하고 캐릭터 몸체의 가각 면과 수직인 벡터 $\vec{b}$ 라 해서 내적을 계산하면 $\vec{a}\cdot\vec{b} < 0$ 이면 시선과 해당 면이 서로 마주 보고 있어서 해당 면을 랜더링해야 한다. 그리고 $\vec{a}\cdot\vec{b} > 0$  이면 시점과 해당면이 같은 방향을 향하고 있으므로 랜더링하지 않아도 된다. 이렇게 계산을 하면 위 그림에서 굵게 표시된 면만 랜더링해도 된다. 

이처럼 그래픽스, 게임 등에서 랜더링 판단에도 사용할 수 있다.

#### 코사인 유사도

내적을 계산한 결과에 따라 두 벡터가 닮았는지 판단하는 수법이 **코사인 유사도**이다. 

- http://euriion.com/?p=548

이것은 아래 같은 데이터에도 적용된다. 아래 표는 다섯 단어로 만든 문장과 특정 단어가 문장에 나타나는 빈도를 정리했다.

_ | 문장 | 파란 | 하얀 | 하늘 | 구름 | 파도
- | ------ | -- | -- | -- | -- | --
문장1 | 파란 하늘과 파란 파도 | 2 | 0 | 1 | 0 | 1
문장2 | 파란 하늘과 하얀 파도 | 1 | 1 | 1 | 0 | 1
문장3 | 하얀 구름과 파란 하늘 | 1 | 1 | 1 | 1 | 0



$$
cos\theta = \frac{ a_1b_1 + a_2b_2}{\left| \vec{a} \right| \left| \vec{b} \right|} \quad \longleftarrow 식4 \\\\
|\vec{a}| = \sqrt{(a_2-a_1)^2 + (b_2-b_1)^2}\\
|\vec{b}| = \sqrt{(a_4-a_3)^2 + (a_4-a_3)^2}
$$

In [32]:
a = np.array([2,0,1,0,1])
b = np.array([1,1,1,0,1])
c = np.array([1,1,1,1,0])

##### 문)  예를 들어 세개의 문서가 있고 각 문서는 a, b, c, d라는 단어로만 구성되어 있다고 합시다.

- 1번 문서는 a가 3번 b가 2번 c가 0번 d가 2번 출현했다고 하고
- 2번 문서는 a가 1번 b가 2번 c가 3번 d가 0번 출현했다고 하고
- 3번 문서는 a가 2번 b가 2번 c가 2번 d가 2번 출현했다고 하면

각 단어의 출현빈도를 속성으로 갖는 문서 D1을 정의하면 다음과 같이 정의할 수 있습니다.
 
```
D1 = { 3, 2, 0, 2 }
D2 = { 1, 2, 3, 0 }
D3 = { 2, 2, 2, 2 }
```
 
질의: "a가 1번 b 5번 나온 문서와 가장 가까운(유사한) 문서는?" 다음과 같이 표현하여 벡터 내적을 적용하면 될 것 같네요.
 
Q = {1, 5, 0 , 0}


##### 풀이1) 

첫번째 방법은 벡터 Q와 다른 문서 벡터와의 사잇각 θ를 이용하기 위해 cosθ 값을 구해서 비교하는 것입니다.


$$
cos\theta = \frac{ a_1b_1 + a_2b_2}{\left| \vec{a} \right| \left| \vec{b} \right|} \quad \longleftarrow 식4 \\\\
|\vec{a}| = \sqrt{(a_2-a_1)^2 + (b_2-b_1)^2}\\
|\vec{b}| = \sqrt{(a_4-a_3)^2 + (a_4-a_3)^2}
$$

In [43]:
cos_qd1 = ((1*3)+(5*2))/(math.sqrt(1+5**2)*math.sqrt(3**2+2**2+2**2))
cos_qd2 = ((1*1)+(5*2))/(math.sqrt(1+5**2)*math.sqrt(1+2**2+3**2))
cos_qd3 = ((1*2)+(5*2))/(math.sqrt(1+5**2)*math.sqrt(2**2+2**2+2**2+2**2))


cos_qd1,cos_qd2,cos_qd3

(0.6183469424008424, 0.5765566601970551, 0.5883484054145521)

계산으로 Q 와 각 문서 벡터 사이 가장 좁은 각은 D1 으로 이것이 질의와 가장 비슷한 것이다.

---

## 4.4 벡터의 외적

1. 외적은 두 벡터에 수직인 벡터가 된다
2. 그 벡터의 크기는 두 벡터가 이루는 평행사변형의 면적과 같다

### 4.4.1 법선벡터

벡터의 외적을 계산하는 것은 벡터의 성분을 x 를 사용해 아래 같이 계산한다.

$$
\vec{a} = \begin{pmatrix} a_1 \\ a_2 \\ a_3 \end{pmatrix},\quad \begin{pmatrix} b_1 \\ b_2 \\ b_3 \end{pmatrix} \\
\\
\vec{a} \times \vec{b} = 
\begin{pmatrix} a_2b_3 - a_3b_2\\
                a_3b_1 - a_1b_3\\
                a_1b_2 - a_2b_1 \end{pmatrix}
$$

이것은 *외적을 계산한 결과는 벡터가된다* 는 점에 주목해야 하고 삼차원 공간에 존재하는 벡터이다.

외적에서 중요한 것은 **외적을 계산한 결과로 나오는 벡터는 두 벡터에 수직인 벡터가 된다**이다. 그리고 **오른속 나사의 법칙**을 따른다. 즉 벡터a에서 벡터b로 오른쪽으로 나사를 돌렸을 때 나사가 진행하는 방향 의미.

<img src='images/vector_outerproduct_dir.JPG' width='300'>

a,b 벡터가 이루는 평행사변형을 평면이라고 생각하면 외적은 계산한 결과로 나온 벡터는 이 면에 수직인 벡터가 된다. 이 벡터를 **법선벡터**라고 한다.

법선벡터는 해당 면이 향하고 있는 방향을 나타내는 값으로 삼차원 그래픽스, 게임의 등에서 물체에 닿는 빛의 각도를 법선벡터 값을 이용해 계산하고 그림자를 표현한다.

<img src='https://image.slidesharecdn.com/normalmapping-170906015645/95/normal-mapping-12-638.jpg?cb=1504663052' width='200'>

파이썬에서 NumPy의 cross() 함수로 외적을 구할 수 있다.

```
numpy.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)
 - cross product of a, b
```

 - https://numpy.org/doc/1.18/reference/generated/numpy.cross.html
 

In [45]:
import numpy as np

a = np.array([0,1,2])
b = np.array([2,0,0])
np.cross(a,b)

array([ 0,  4, -2])

### 4.4.2 면적 구하기

벡터의 외적의 결과로 나온 벡터는 **두 벡터가 이루는 평행사변형의 면적과 같다**이다.

$$
\left| \vec{a}\times \vec{b}\right| = \left|\vec{a}\right|\left|\vec{b}\right|sin\theta \quad \longleftarrow 식5
$$


<img src='images/vector_two_vector_parallelogram.png' width='300'>

이 계산식은 벡터a 끝에서 벡터b로 수선을 내리면 수선의 길이 h를 삼각비를 이용해 아래 같이 나타낼 수 있다. h는 평행사변형의 높이이다. 평행사변형 밑변은 벡터b이고 크기/길이는 $|\vec{b}|$ 이다. 

$$
sin\theta = \frac{h}{|\vec{a}|} \\
h = |\vec{a}| sin\theta
$$

평행사변형 면적은 *밑변X높이* 이므로 $|\vec{a}||\vec{b}| sin\theta$ 가 되어 위 식5의 우변과 같아진다.

##### 문)

그림에서 두 벡터의 끝점을 이어 만든 삼각형(색칠한 부분)의 면적을 구해보자,

<img src='images/vector_ex_parallelogram.png' width='300'>

구하는 순서:
1. 두 벡터의 크기를 구한다
2. 벡터의 내적을 이용해 두 벡터가 이루는 각도를 구한다.
3. 외적 공식 $|\vec{a}||\vec{b}| sin\theta$  이용해 평행사변형 면적을 구한다.

NumPy를 이용해 벡터의 외적은 cross()를 이용하고, 벡터의 크기는 norm() 을 사용한다.

In [48]:
a = np.array([2,4])
b = np.array([3,1])
#외적
cross_ab = np.cross(a,b)
#벡터 크기
s_ab = np.linalg.norm(cross_ab) # 외적의 크기
#삼각형 크기
s_ab / 2

5.0

---

# 참고

- [김대수의 수학 어드벤쳐] 벡터 개념, 르네상스 이후 등장 … 현수교 설계 때 필수
  - https://news.joins.com/article/18169742